const SUPABASE_URL='https://qilylafyygmxgtwgosvt.supabase.co';
const SUPABASE_KEY='sb_publishable_45w093agTkMtioWxrvsBIQ_QjzcWKO9';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const app=document.getElementById('app');
const LS='spesa_v1_local';
let session=null,page='home',draft=null,mode='cloud',categories=[];
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const dateIT=d=>d?new Intl.DateTimeFormat('it-IT').format(new Date(d+'T12:00:00')):'';
const iso=d=>new Date(d).toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const local=()=>JSON.parse(localStorage.getItem(LS)||'{"receipts":[],"budget":0}');
const saveLocal=x=>localStorage.setItem(LS,JSON.stringify(x));
function nav(){return `<nav class="nav"><button class="${page==='home'?'active':''}" onclick="go('home')">Home</button><button class="${page==='import'?'active':''}" onclick="go('import')">Scontrino</button><button class="${page==='receipts'?'active':''}" onclick="go('receipts')">Spese</button><button class="${page==='products'?'active':''}" onclick="go('products')">Prodotti</button><button onclick="setBudget()">Budget</button></nav>`}
function bottom(){return `<nav class="bottom"><button class="${page==='home'?'active':''}" onclick="go('home')">Home</button><button class="${page==='import'?'active':''}" onclick="go('import')">Scontrino</button><button class="${page==='receipts'?'active':''}" onclick="go('receipts')">Spese</button><button class="${page==='products'?'active':''}" onclick="go('products')">Prodotti</button></nav>`}
const defaultSpesaCategories=['Alternative vegetali','Altro','Animali','Bevande','Carne','Casa','Condimenti','Cura della persona','Dispensa','Dolci e snack','Frutta','Latticini','Legumi','Pane e prodotti da forno','Pasta e cereali','Pesce','Surgelati','Uova','Verdura'];
async function loadCategories(){
  if(mode==='local'){categories=defaultSpesaCategories.map((name,i)=>({id:`local-cat-${i}`,name}));return}
  const {data,error}=await db.from('spesa_categories').select('id,name').eq('user_id',session.user.id).order('name');
  if(error){console.error(error);categories=[];return}
  categories=data||[];
  if(!categories.length){
    const rows=defaultSpesaCategories.map(name=>({id:crypto.randomUUID(),user_id:session.user.id,name,is_food:true}));
    const r=await db.from('spesa_categories').insert(rows).select('id,name').order('name');
    if(!r.error)categories=r.data||[];
  }
}
async function boot(){const {data}=await db.auth.getSession();if(data.session){session=data.session;mode='cloud'}else{const r=await db.auth.signInAnonymously();if(!r.error){session=r.data.session;mode='cloud'}else{mode='local'}}await loadCategories();render()}
function go(p){page=p;render()}
async function render(){app.innerHTML=`${nav()}<main class="main"><div id="content"></div></main>${bottom()}`;const c=document.getElementById('content');if(page==='home')return dashboard(c);if(page==='import')return importPage(c);if(page==='receipts')return receiptsPage(c);if(page==='products')return productsPage(c)}
async function getReceipts(){if(mode==='local')return local().receipts;const {data,error}=await db.from('spesa_receipts').select('*').eq('user_id',session.user.id).order('purchase_date',{ascending:false});if(error){mode='local';return local().receipts}return data||[]}
async function dashboard(c){const rows=await getReceipts();const now=new Date(),month=now.toISOString().slice(0,7),weekStart=new Date(now);weekStart.setDate(now.getDate()-((now.getDay()+6)%7));const monthRows=rows.filter(r=>String(r.purchase_date).slice(0,7)===month);const weekRows=rows.filter(r=>new Date(r.purchase_date+'T12:00:00')>=weekStart);const totalMonth=monthRows.reduce((s,r)=>s+Number(r.total_amount),0),totalWeek=weekRows.reduce((s,r)=>s+Number(r.total_amount),0);const budget=mode==='local'?Number(local().budget||0):await getBudget();c.innerHTML=`<div class="top"><div><h1 class="title">Spesa</h1><div class="muted">${new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}).format(now)}</div></div><button class="btn" onclick="go('import')">+ Scontrino</button></div><div class="grid"><div class="card"><div class="label">Questa settimana</div><div class="kpi">${money(totalWeek)}</div></div><div class="card"><div class="label">Questo mese</div><div class="kpi">${money(totalMonth)}</div></div><div class="card"><div class="label">Budget mensile</div><div class="kpi">${budget?money(budget):'—'}</div><div class="muted small">${budget?money(Math.max(0,budget-totalMonth))+' disponibili':'Tocca Budget per impostarlo'}</div></div><div class="card"><div class="label">Scontrini</div><div class="kpi">${monthRows.length}</div></div></div><div class="card section"><div class="section-title">Ultimi scontrini</div>${rows.slice(0,8).map(r=>`<div class="row"><span>${dateIT(r.purchase_date)}</span><strong>${money(r.total_amount)}</strong></div>`).join('')||'<div class="empty">Nessuno scontrino ancora.</div>'}</div><div class="card section"><div class="section-title">Regola dell'app</div><p class="muted">Tutti i prodotti appartengono alla stessa spesa. Le categorie sono neutre e vengono scelte da te. L'OCR non decide se un prodotto è alimentare o non alimentare.</p></div>`}
async function getBudget(){if(!session)return 0;const month=new Date().toISOString().slice(0,7)+'-01';const {data}=await db.from('spesa_budgets').select('amount').eq('user_id',session.user.id).eq('month',month).maybeSingle();return Number(data?.amount||0)}
async function setBudget(){const current=mode==='local'?Number(local().budget||0):await getBudget();const value=prompt('Budget mensile in euro',current||'');if(value===null)return;const amount=Math.max(0,Number(value.replace(',','.'))||0);if(mode==='local'){const x=local();x.budget=amount;saveLocal(x);return render()}const month=new Date().toISOString().slice(0,7)+'-01';await db.from('spesa_budgets').upsert({user_id:session.user.id,month,amount},{onConflict:'user_id,month'});render()}
function importPage(c){c.innerHTML=`<div class="top"><div><h1 class="title">Importa scontrino</h1><div class="muted">Foto, controllo manuale, salvataggio.</div></div></div><div class="card drop"><div>Seleziona una foto dello scontrino.</div><input type="file" accept="image/*" capture="environment" onchange="scan(this.files[0])"><p class="muted small">L'OCR propone solo data, totale e righe. Non assegna categorie.</p></div>`}
async function scan(file){if(!file)return;const c=document.getElementById('content');c.innerHTML=`<div class="card"><div class="section-title">Lettura scontrino</div><p id="progress">Sto leggendo…</p></div>`;try{const result=await Tesseract.recognize(file,'ita',{logger:m=>{if(m.status==='recognizing text')document.getElementById('progress').textContent=`Lettura ${Math.round((m.progress||0)*100)}%…`}});const text=result.data.text;draft={date:findDate(text)||iso(new Date()),total:findTotal(text),market:findMarket(text),raw:text,imageUrl:URL.createObjectURL(file),items:parseItems(text)};review()}catch(e){console.error(e);c.innerHTML=`<div class="notice">OCR non disponibile. Inserisci i dati manualmente.</div><button class="btn" onclick="manualReceipt()">Inserisci scontrino</button>`}}
function findDate(t){const m=t.match(/\b(\d{1,2})[/.](\d{1,2})[/.](20\d{2})\b/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:null}
function findTotal(t){const lines=t.split(/\n/).map(x=>x.trim());for(let i=lines.length-1;i>=0;i--){const m=lines[i].match(/(?:totale|total[eè]|da pagare|pagamento)[^\d]*(\d+[.,]\d{2})/i);if(m)return Number(m[1].replace(',','.'))}const nums=[...t.matchAll(/\b\d+[.,]\d{2}\b/g)].map(m=>Number(m[0].replace(',','.')));return nums.length?Math.max(...nums):0}
function findMarket(t){const x=t.toLowerCase();for(const n of ['Esselunga','Carrefour','Conad','Lidl','Coop','Eurospin','Iper','Pam'])if(x.includes(n.toLowerCase()))return n;return ''}
function parseItems(t){const skip=/totale|pagamento|contanti|resto|iva|sconto|coupon|tessera|punti|shopper|documento|partita iva|p\.i\.|www\.|www|grazie|servizio/i;const out=[];for(const raw of t.split(/\n/)){let line=raw.replace(/\s+/g,' ').trim();if(!line||skip.test(line))continue;const matches=[...line.matchAll(/(\d+[.,]\d{2})/g)];if(!matches.length)continue;const last=matches[matches.length-1];const price=Number(last[1].replace(',','.'));if(!Number.isFinite(price)||price<=0||price>999)continue;let name=line.slice(0,last.index).replace(/^[*x×\s]+|[*x×\s]+$/g,'').trim();if(name.length<2||/^\d+$/.test(name))continue;const q=(name.match(/^(\d+)\s*x\s*/i)||[])[1];if(q)name=name.replace(/^\d+\s*x\s*/i,'').trim();out.push({name,qty:q?Number(q):1,price,categoryId:null});}return out}
function manualReceipt(){draft={date:iso(new Date()),total:0,market:'',raw:'',imageUrl:'',items:[]};review()}
function categoryOptions(selected=''){return `<option value="">Senza categoria</option>${categories.map(cat=>`<option value="${esc(cat.id)}" ${cat.id===selected?'selected':''}>${esc(cat.name)}</option>`).join('')}`}
function review(){const c=document.getElementById('content');c.innerHTML=`<div class="top"><div><h1 class="title">Controlla scontrino</h1><div class="muted">Assegna le categorie manualmente, se vuoi.</div></div><div class="actions"><button class="btn secondary" onclick="go('home')">Annulla</button><button class="btn" onclick="saveReceipt()">Salva</button></div></div><div class="two"><div class="card">${draft.imageUrl?`<img class="thumb" src="${draft.imageUrl}">`:''}<div class="form" style="margin-top:16px"><div class="field"><label>Data</label><input id="rdate" type="date" value="${draft.date}"></div><div class="field"><label>Supermercato</label><input id="rmarket" value="${esc(draft.market)}"></div><div class="field"><label>Totale scontrino</label><input id="rtotal" type="number" step="0.01" value="${draft.total}"></div></div></div><div class="card"><div class="section-title">Prodotti letti</div><p class="muted small">Nome, quantità, prezzo e categoria sono modificabili. La categoria è sempre scelta manualmente.</p><div class="review-list" id="items">${draft.items.map((it,i)=>`<div class="review-row"><input value="${esc(it.name)}" data-name="${i}" aria-label="Nome prodotto"><input type="number" step="1" min="1" value="${it.qty}" data-qty="${i}" aria-label="Quantità"><input type="number" step="0.01" value="${it.price.toFixed(2)}" data-price="${i}" aria-label="Prezzo"><select data-category="${i}" aria-label="Categoria">${categoryOptions(it.categoryId||'')}</select></div>`).join('')}</div><button class="btn secondary" style="margin-top:14px" onclick="addItem()">+ Prodotto</button></div></div>`}
function addItem(){readReview();draft.items.push({name:'',qty:1,price:0,categoryId:null});review()}
function readReview(){draft.date=document.getElementById('rdate').value;draft.market=document.getElementById('rmarket').value;draft.total=Number(document.getElementById('rtotal').value)||0;draft.items=draft.items.map((it,i)=>({name:document.querySelector(`[data-name="${i}"]`)?.value||it.name,qty:Number(document.querySelector(`[data-qty="${i}"]`)?.value)||1,price:Number(document.querySelector(`[data-price="${i}"]`)?.value)||0,categoryId:document.querySelector(`[data-category="${i}"]`)?.value||it.categoryId||null})).filter(x=>x.name.trim())}
async function saveReceipt(){readReview();if(!draft.date||draft.total<=0){alert('Inserisci almeno data e totale.');return}if(mode==='local'){const x=local();x.receipts.unshift({id:crypto.randomUUID(),purchase_date:draft.date,total_amount:draft.total,market:draft.market,items:draft.items});saveLocal(x);draft=null;return go('home')}const supermarketId=await saveMarket(draft.market);const {data:r,error}=await db.from('spesa_receipts').insert({user_id:session.user.id,supermarket_id:supermarketId,purchase_date:draft.date,total_amount:draft.total,food_amount:draft.total,non_food_amount:0,raw_ocr:draft.raw,status:'saved'}).select().single();if(error){alert('Errore nel salvataggio: '+error.message);return}for(const it of draft.items){let productId=null;const {data:p}=await db.from('spesa_products').select('id,category_id').eq('user_id',session.user.id).ilike('name',it.name).maybeSingle();if(p){productId=p.id;if(!it.categoryId&&p.category_id)it.categoryId=p.category_id}else{const {data:np}=await db.from('spesa_products').insert({user_id:session.user.id,name:it.name,category_id:it.categoryId||null,is_food:true}).select('id').single();productId=np?.id||null}if(productId&&it.categoryId){await db.from('spesa_products').update({category_id:it.categoryId}).eq('id',productId).eq('user_id',session.user.id)}await db.from('spesa_receipt_items').insert({receipt_id:r.id,user_id:session.user.id,product_id:productId,raw_description:it.name,category_id:it.categoryId||null,quantity:it.qty,unit_price:it.price/it.qty,line_total:it.price,price_per_base_unit:null,is_food:true,discount_ignored:false});}draft=null;go('home')}
async function saveMarket(name){if(!name||!session)return null;const {data}=await db.from('spesa_supermarkets').select('id').eq('user_id',session.user.id).ilike('name',name).maybeSingle();if(data)return data.id;const {data:n}=await db.from('spesa_supermarkets').insert({user_id:session.user.id,name}).select('id').single();return n?.id||null}
async function receiptsPage(c){const rows=await getReceipts();c.innerHTML=`<div class="top"><div><h1 class="title">Spese</h1><div class="muted">Tutti gli scontrini, senza distinzione alimentare.</div></div><button class="btn" onclick="go('import')">+ Scontrino</button></div><div class="card">${rows.map(r=>`<div class="row"><span>${dateIT(r.purchase_date)}</span><strong>${money(r.total_amount)}</strong></div>`).join('')||'<div class="empty">Nessuno scontrino.</div>'}</div>`}
async function productsPage(c){
  let products=[];
  if(mode==='local'){
    const rows=local().receipts;const map={};
    rows.forEach(r=>(r.items||[]).forEach(i=>{const k=i.name.toLowerCase();map[k]??={name:i.name,total:0,count:0,categoryId:i.categoryId||null};map[k].total+=i.price;map[k].count+=i.qty;if(!map[k].categoryId&&i.categoryId)map[k].categoryId=i.categoryId}));
    products=Object.values(map);
  }else{
    const {data,error}=await db.from('spesa_products').select('id,name,category_id').eq('user_id',session.user.id).order('name');
    if(error){console.error(error)}
    const {data:items}=await db.from('spesa_receipt_items').select('product_id,line_total,quantity,category_id').eq('user_id',session.user.id);
    const map={};
    for(const p of data||[])map[p.id]={id:p.id,name:p.name,total:0,count:0,categoryId:p.category_id||null};
    for(const i of items||[])if(map[i.product_id]){map[i.product_id].total+=Number(i.line_total);map[i.product_id].count+=Number(i.quantity);if(!map[i.product_id].categoryId&&i.category_id)map[i.product_id].categoryId=i.category_id}
    products=Object.values(map);
  }
  const grouped={};
  products.forEach(p=>{const key=p.categoryId||'__none';(grouped[key]??=[]).push(p)});
  const orderedKeys=categories.map(x=>x.id).filter(id=>grouped[id]?.length);if(grouped.__none?.length)orderedKeys.push('__none');
  c.innerHTML=`<div class="top"><div><h1 class="title">Prodotti</h1><div class="muted">Le categorie restano, ma non esiste alcuna distinzione alimentare.</div></div></div><div class="card"><p class="muted small">Assegna o cambia la categoria di ogni prodotto. L'app non decide automaticamente.</p>${orderedKeys.map(key=>`<div class="category-block"><div class="section-title">${key==='__none'?'Senza categoria':esc(categories.find(x=>x.id===key)?.name||'Senza categoria')}</div>${grouped[key].map(p=>`<div class="product-row"><div class="product-main"><span class="product-name">${esc(p.name)}</span><span class="muted small">${money(p.total)} · ${p.count} pz</span></div><select onchange="updateProductCategory('${esc(p.id||'').trim()}',this.value)" ${mode==='local'?'disabled':''}>${categoryOptions(p.categoryId||'')}</select></div>`).join('')}</div>`).join('')||'<div class="empty">Nessun prodotto ancora.</div>'}</div>`;
}
async function updateProductCategory(productId,categoryId){productId=String(productId).trim();if(mode==='local')return;const {error}=await db.from('spesa_products').update({category_id:categoryId||null}).eq('id',productId).eq('user_id',session.user.id);if(error){alert('Errore nel salvataggio: '+error.message);return}await db.from('spesa_receipt_items').update({category_id:categoryId||null}).eq('product_id',productId).eq('user_id',session.user.id);await productsPage(document.getElementById('content'))}
boot();
