const SUPABASE_URL='https://qilylafyygmxgtwgosvt.supabase.co';
const SUPABASE_KEY='sb_publishable_45w093agTkMtioWxrvsBIQ_QjzcWKO9';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const app=document.getElementById('app');
let session=null,page='home',mode='cloud';
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const dateIT=d=>d?new Intl.DateTimeFormat('it-IT').format(new Date(d+'T12:00:00')):'';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function nav(){return `<nav class="nav"><button class="${page==='home'?'active':''}" onclick="go('home')">Home</button><button class="${page==='receipts'?'active':''}" onclick="go('receipts')">Spese</button><button class="${page==='products'?'active':''}" onclick="go('products')">Prodotti</button></nav>`}
function go(p){page=p;render()}
async function boot(){const {data}=await db.auth.getSession();if(data.session){session=data.session;mode='cloud'}else{const r=await db.auth.signInAnonymously();if(!r.error){session=r.data.session;mode='cloud'}else mode='local'}render()}
async function getReceipts(){if(mode==='local')return [];const {data,error}=await db.from('spesa_receipts').select('id,purchase_date,total_amount,food_amount,non_food_amount,supermarket_id').eq('user_id',session.user.id).order('purchase_date',{ascending:false});if(error){console.error(error);return []}return data||[]}
async function getItems(){const {data,error}=await db.from('spesa_receipt_items').select('id,receipt_id,product_id,raw_description,brand_id,category_id,quantity,package_amount,package_unit,unit_price,line_total,price_per_base_unit,is_food,discount_ignored').eq('user_id',session.user.id);if(error){console.error(error);return []}return data||[]}
async function getLookups(){const [s,c,b,p]=await Promise.all([db.from('spesa_supermarkets').select('id,name').eq('user_id',session.user.id),db.from('spesa_categories').select('id,name').eq('user_id',session.user.id),db.from('spesa_brands').select('id,name').eq('user_id',session.user.id),db.from('spesa_products').select('id,name,brand_id,category_id,normalized_unit,normalized_amount,normalized_unit_price').eq('user_id',session.user.id)]);return {supermarkets:s.data||[],categories:c.data||[],brands:b.data||[],products:p.data||[]}}
function mapBy(a){return Object.fromEntries(a.map(x=>[x.id,x]))}
function suggestCategory(name){const n=String(name||'').toLowerCase();if(/latte|philadelphia|skyr|muller|kefir|yogurt|formaggio|ricotta/.test(n))return 'Latticini';if(/mela|banana|pesche|lamponi|fragol|arancia|pera|frutta/.test(n))return 'Frutta';if(/zucchin|insalat|verdur|minestrone/.test(n))return 'Verdura';if(/germogli/.test(n))return 'Alternative vegetali';if(/pollo|carne|prosciutt|hamburger/.test(n))return 'Carne';if(/salmone|tonno|pesce/.test(n))return 'Pesce';if(/farro|avena|pasta|riso|cereali|zuppa/.test(n))return 'Pasta e cereali';if(/biscott|cioccol|dess|snack|dolc/.test(n))return 'Dolci e snack';if(/carta|fazz|scott|shopper|sacchetto|buste|bolle|perle|tempo|carta ig/.test(n))return 'Casa';return 'Altro'}
function categoryFor(item,lookups){return lookups.categories.find(c=>c.id===item.category_id)?.name||suggestCategory(item.raw_description)}
async function dashboard(c){const [rows,items,lk]=await Promise.all([getReceipts(),getItems(),getLookups()]);const now=new Date(),month=now.toISOString().slice(0,7);const weekStart=new Date(now);weekStart.setDate(now.getDate()-((now.getDay()+6)%7));weekStart.setHours(0,0,0,0);const monthRows=rows.filter(r=>String(r.purchase_date).slice(0,7)===month);const weekRows=rows.filter(r=>new Date(r.purchase_date+'T12:00:00')>=weekStart);const totalMonth=monthRows.reduce((s,r)=>s+Number(r.total_amount),0);const totalWeek=weekRows.reduce((s,r)=>s+Number(r.total_amount),0);const foodMonth=monthRows.reduce((s,r)=>s+Number(r.food_amount),0);const nonFoodMonth=monthRows.reduce((s,r)=>s+Number(r.non_food_amount),0);const monthIds=new Set(monthRows.map(r=>r.id));const catTotals={};for(const it of items.filter(i=>monthIds.has(i.receipt_id))){const cat=categoryFor(it,lk);catTotals[cat]=(catTotals[cat]||0)+Number(it.line_total)}const topCats=Object.entries(catTotals).sort((a,b)=>b[1]-a[1]).slice(0,6);const supermarket=mapBy(lk.supermarkets);const supermarketTotals={};for(const r of monthRows){const n=supermarket[r.supermarket_id]?.name||'Non indicato';supermarketTotals[n]=(supermarketTotals[n]||0)+Number(r.total_amount)}c.innerHTML=`<div class="top"><div><h1 class="title">Spesa</h1><div class="muted">${new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}).format(now)}</div></div></div><div class="grid"><div class="card"><div class="label">Questa settimana</div><div class="kpi">${money(totalWeek)}</div></div><div class="card"><div class="label">Questo mese</div><div class="kpi">${money(totalMonth)}</div></div><div class="card"><div class="label">Alimentari</div><div class="kpi">${money(foodMonth)}</div></div><div class="card"><div class="label">Non alimentari</div><div class="kpi">${money(nonFoodMonth)}</div></div></div><div class="two section"><div class="card"><div class="section-title">Categorie più costose</div>${topCats.length?topCats.map(([n,v])=>`<div class="row"><span>${esc(n)}</span><strong>${money(v)}</strong></div>`).join(''):'<div class="empty">Nessun dato.</div>'}</div><div class="card"><div class="section-title">Supermercati</div>${Object.entries(supermarketTotals).sort((a,b)=>b[1]-a[1]).map(([n,v])=>`<div class="row"><span>${esc(n)}</span><strong>${money(v)}</strong></div>`).join('')||'<div class="empty">Nessun dato.</div>'}</div></div><div class="card section"><div class="section-title">Ultimi scontrini</div>${rows.slice(0,8).map(r=>`<div class="row"><span>${dateIT(r.purchase_date)} · ${esc(supermarket[r.supermarket_id]?.name||'Non indicato')}</span><strong>${money(r.total_amount)}</strong></div>`).join('')||'<div class="empty">Nessuno scontrino ancora.</div>'}</div><div class="notice neutral">MVP: per ora l'OCR è disattivato. Mandami qui la foto dello scontrino. Estraggo io i dati e li inserisco direttamente nel database.</div>`}
async function receiptsPage(c){const [rows,lk]=await Promise.all([getReceipts(),getLookups()]);const supermarket=mapBy(lk.supermarkets);c.innerHTML=`<div class="top"><div><h1 class="title">Spese</h1><div class="muted">Storico degli scontrini</div></div></div><div class="card">${rows.map(r=>`<div class="row receipt-row"><div><b>${dateIT(r.purchase_date)}</b><div class="muted">${esc(supermarket[r.supermarket_id]?.name||'Supermercato non indicato')} · alimentari ${money(r.food_amount)}</div></div><strong>${money(r.total_amount)}</strong></div>`).join('')||'<div class="empty">Nessuno scontrino.</div>'}</div>`}
async function productsPage(c){const [items,lk]=await Promise.all([getItems(),getLookups()]);const products=mapBy(lk.products),brands=mapBy(lk.brands);const grouped={};for(const it of items){const p=products[it.product_id];const key=it.product_id||it.raw_description;const name=p?.name||it.raw_description;(grouped[key]??={name,brand:brands[it.brand_id||p?.brand_id]?.name||'',category:categoryFor(it,lk),prices:[]});grouped[key].prices.push(Number(it.unit_price))}const list=Object.values(grouped).sort((a,b)=>a.name.localeCompare(b.name,'it'));c.innerHTML=`<div class="top"><div><h1 class="title">Prodotti</h1><div class="muted">Marca, categoria e andamento dei prezzi</div></div></div><div class="card">${list.map(p=>{const avg=p.prices.reduce((a,b)=>a+b,0)/p.prices.length;const min=Math.min(...p.prices),max=Math.max(...p.prices);return `<div class="product-row"><div class="product-main"><div class="product-name">${esc(p.name)}</div><div class="muted">${esc(p.brand||'Marca non indicata')} · ${esc(p.category)}</div></div><div class="price-block"><b>${money(avg)}</b><span class="muted">${p.prices.length>1?`media · ${money(min)}–${money(max)}`:'ultimo prezzo'}</span></div></div>`}).join('')||'<div class="empty">Nessun prodotto ancora.</div>'}</div>`}
function render(){app.innerHTML=`${nav()}<main class="main"><div id="content"></div></main>`;const c=document.getElementById('content');if(page==='home')return dashboard(c);if(page==='receipts')return receiptsPage(c);return productsPage(c)}
boot();